name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential

  compile:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile with Makefile
        run: make

      - name: Build Docker image with compiled binary
        run: docker build -t compiled-app .

  docker:
    runs-on: ubuntu-latest
    needs: compile

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Load Docker image
        run: docker load -i compiled-app.tar

      - name: List Docker images
        run: docker images

      - name: Run Docker container
        run: docker run compiled-app
