name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: install build tools
      run: sudo apt-get update && sudo apt-get install -y build-essential

  compile:

    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: checkout code
      uses: actions/checkout@v4
      
    - name: run makefile
      run: make
    
  
