name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: install build tools
      run: sudo apt-get update && sudo apt-get install -y build-essential
      
  compile:

    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: checkout code
      uses: actions/checkout@v4
      
    - name: run makefile
      run: make

    - name: Upload compiled binary
      uses: actions/upload-artifact@v2
      with:
        name: compiled-app
        path: ABC.exe

  docker:

    runs-on: ubuntu-latest
    needs: compile

    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: Download compiled binary
      uses: actions/download-artifact@v2
      with:
        name: compiled-app

    - name: build docker image
      run: docker build -t my_app:latest .
  
   
  
    
  
